#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Prototype1.Resource", IsApplication=true)]

namespace Prototype1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int txtInputWidth = 2130968578;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int prototype1_bg = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int ImageView01 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int TextView01 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int TextView02 = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int btnGo = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int imageView2 = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int textView1 = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int txtInput = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int txtOutput = 2131165187;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int Go = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Input = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int Output = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Transform = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int action_settings = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int hello_world = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int imgArrow = 2131034115;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
