# config.make generated by configure script
POCO_CONFIG = iPhone
POCO_BASE = /Users/exjobb/poco-1.5.1-all2
POCO_BUILD = /Users/exjobb/poco-1.5.1-all2
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = CppParser CodeGeneration Remoting/RemoteGen Crypto NetSSL_OpenSSL Data/ODBC Data/MySQL
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
